### PR TITLE
Update UI icons

### PR DESCRIPTION
**Pull request by dentalala**
screenshots

This pull request proposes new interface icons in tab bar, navigation bar, and swipe actions. It also updates original app icon with pixel-perfect kerning of shapes for every icon size.

### CODE REVIEW

**Comment by hartlco** [comment]
To consider this pull request it needs to include the the source (sketch file, psd) for the icons. Otherwise I don't have the guarantee that it's future proof. (maybe a @4x scaler in the cute and so on)
The source for the icons need to be released under the MIT license as well.

**Comment by dentalala** [comment]
The source file is already there, see .sketch. ;)

**Comment by hartlco** [comment]
Ah, I'm very sorry! I'll give it a close look 😄

**Comment by hartlco** [comment]
Sorry for the late response again. I'm still not decided as I'm not really a designer and it's hard for me to judge.
I asked the micro.blog community what they think :)
[Link](https://hartl.co/contents/2018/10/14/18-46.html)

**Comment by ai** [comment]
New menu icons looks more balanced (have the same black/white ratio) :+1:

**Comment by dentalala** [comment]
Sure! Let community decide. This is what I really like about open-sourced software. I hope I can help making this great app even better.

**Comment by paulrobertlloyd** [comment]
Looks good to me! I really like the mentions icon, too 😀

**Comment by hartlco** [comment]
I finally merged it! Thank you Dan for your work and patience.
Also thank you for everyone who voted!

I made some small changes after merging:
- Undid the changes to the App icon and included the original App icon into the sketch file
- Undid the changes of the readme, I want to update the App Store screenshots now as well and will also update the readme one then

**Pull request merged**
